### ISSUE TITLE
Examples in preprocessing jupyter notebook ShapeError

### ISSUE THREAD

**Issue by FangyangJz** [functime-org/functime#188] opened 2024-03-21 22:46 UTC
**Describe the bug**
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Cell In[9], [line 3](vscode-notebook-cell:?execution_count=9&line=3)
      [1](vscode-notebook-cell:?execution_count=9&line=1) transformer = detrend(freq="1mo", method="linear")
      [2](vscode-notebook-cell:?execution_count=9&line=2) y_detrended = y.pipe(transformer).collect()
----> [3](vscode-notebook-cell:?execution_count=9&line=3) figure = plot_forecasts(
      [4](vscode-notebook-cell:?execution_count=9&line=4)     y_true=y, y_pred=y_detrended.group_by(entity_col).tail(64), height=800, width=1000
      [5](vscode-notebook-cell:?execution_count=9&line=5) )
      [6](vscode-notebook-cell:?execution_count=9&line=6) figure.show(renderer="svg")

File [c:\Users\fangy\miniconda3\envs\avalon311\Lib\site-packages\functime\plotting.py:192](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:192), in plot_forecasts(y_true, y_pred, n_series, seed, n_cols, last_n, **kwargs)
    [189](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:189) # Get most recent observations
    [190](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:190) entities = y_true.select(pl.col(entity_col).unique(maintain_order=True)).collect()
--> [192](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:192) entities_sample = entities.to_series().sample(n_series, seed=seed)
    [194](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:194) # Get most recent observations
    [195](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:195) y = (
    [196](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:196)     y_true.filter(pl.col(entity_col).is_in(entities_sample))
    [197](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:197)     .group_by(entity_col)
    [198](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:198)     .tail(last_n)
    [199](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:199)     .collect()
    [200](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/functime/plotting.py:200) )

File [c:\Users\fangy\miniconda3\envs\avalon311\Lib\site-packages\polars\series\utils.py:107](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/series/utils.py:107), in call_expr.<locals>.wrapper(self, *args, **kwargs)
    [105](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/series/utils.py:105)     expr = getattr(expr, namespace)
    [106](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/series/utils.py:106) f = getattr(expr, func.__name__)
...
   [1934](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/lazyframe/frame.py:1934) if background:
   [1935](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/lazyframe/frame.py:1935)     return InProcessQuery(ldf.collect_concurrently())
-> [1937](file:///C:/Users/fangy/miniconda3/envs/avalon311/Lib/site-packages/polars/lazyframe/frame.py:1937) return wrap_df(ldf.collect())

ShapeError: cannot take a larger sample than the total population when `with_replacement=false`

**To Reproduce**
run docs notebooks preprocessing.ipynb

**Expected behavior**
pass

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version 
 - functime     0.9.5
 - polars         0.20.16 
 - plotly          5.19.0

**Comment by yangpu** [comment] 2024-03-28 07:12
The same issue on Mac M1:
`
ShapeError: cannot take a larger sample than the total population when "with_replacement=false"
`

Set n_series=4:
`
figure = plot_panel(y=y, height=800, width=1000, n_series=4)
`
throw error:
`
TypeError: the truth value of a DataFrame is ambiguous
`

**Comment by baggiponte** [comment] 2024-04-16 19:51
Ciao! Sorry for the late reply. Turns out, this maps to #179 and @miroslaavi prepared a PR for this.

**Comment by baggiponte** [comment] 2024-04-22 22:28
Ciao, we might have a fix online for tomorrow 😊

**Comment by baggiponte** [comment] 2024-04-27 09:51
Ciao! Thanks to @miroslaavi, the issue is fixed. Will be in the next release 🚀

**Closed by baggiponte** 2024-04-27 09:51 UTC
Labels: documentation
